### ISSUE TITLE
Build: Update build process to use pipeline YAML file

### ISSUE THREAD

**Issue by russellseymour** [chef-partners/azure-managed-automate#32]
Rename the repo to `chef-partners/camsa-templates` so that all camsa related repos follow the same naming convention.

Update the build so that it uses a pipeline yaml file.

**Comment by russellseymour** [comment]
Additionally test to see if Hosted Agents can be used for the builds, if necessary a container can be used in the configuration.

**Comment by stuartpreston** [comment]
@russellseymour Can this be closed now?

**Comment by russellseymour** [comment]
@stuartpreston Not at the moment as I have not built the Pipeline using a YAML file and have not fully tested using Hosted Agents
