### ISSUE TITLE
Modify release so that artifacts are uploaded to the Azure Cloud Partner Portal

### ISSUE THREAD

**Issue by russellseymour** [chef-partners/azure-managed-automate#35]
Using this page as a reference - https://docs.microsoft.com/en-us/azure/marketplace/cloud-partner-portal-orig/cloud-partner-portal-api-overview, modify the release process so that packages are automatically updated in the portal.

This will only be done via a trigger for the staging deployment, for a production release this will have to be manually triggered

**Comment by stuartpreston** [comment]
This functionality is in the latest build.
