### ISSUE TITLE
Backups should be deleted using chef-automate cli to ensure ES snapshot deletion

### ISSUE THREAD

**Issue by stuartpreston** [chef-partners/azure-managed-automate#39]
Related: #19 
As per internal discussion about this: 

When deleting backups be sure to use `chef-automate backup delete`, deleting the backup directories manually will leave the ES snapshots behind and will then have to be manually deleting using curl requests

We need to improve our backup.sh script to meet the above recommendation.

**Comment by russellseymour** [comment]
This has been fixed in PR #44
